version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    container_name: together-php
    expose:
      - "9000"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    container_name: together-nginx
    ports:
      - "2724:80" # host â†’ container
    depends_on:
      - php

  db:
    image: bitnami/mariadb:latest
    container_name: together-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: together
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
    volumes:
      - db_data:/bitnami/mariadb

volumes:
  db_data:
