version: "3.9"

services:
  php:
    container_name: together-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        HOST_UID: ${UID:-1000}
        HOST_GID: ${GID:-1000}
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    container_name: together-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "2724:80" # host port â†’ container
    volumes:
      - .:/var/www/html
    depends_on:
      - php

  db:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: together
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/bitnami/mariadb

volumes:
  db_data:
