services:
  app:
    container_name: together
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    ports:
      - "2724:80" # Expose Laravel externally
    volumes:
      - .:/var/www/html
      # - laravel_env:/var/www/html/.env
    environment:
      DB_HOST: together_prod_db
      DB_DATABASE: together
      DB_USERNAME: laravel
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: bitnami/mariadb:latest
    container_name: together_prod_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: together
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/bitnami/mariadb

volumes:
  db_data:
  laravel_env:
