version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        HOST_UID: 1000
        HOST_GID: 1000
        COMPOSER_DEV: false
    ports:
      - "9000:9000"  # optional if you want to expose PHP-FPM
    # no volume, code baked in

  nginx:
    image: nginx:alpine
    ports:
      - "2724:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: together
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
    volumes:
      - db_data:/bitnami/mariadb

volumes:
  db_data:
