# docker-compose.yml
# ------------------
services:
  together_api:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        HOST_UID: ${UID:-1000}
        HOST_GID: ${GID:-1000}
    container_name: together_api
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_PROCESS_TIMEOUT: 900
      # COMPOSER_AUTH: '{"github-oauth":{"github.com":"${GITHUB_TOKEN}"}}'
      GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
    volumes:
      - ./:/var/www/html
      - ${HOME}/.ssh:/root/.ssh:ro
      - ${HOME}/.composer:/root/.composer
    ports:
      - "9000:9000" # PHP-FPM port exposed for Nginx
    networks:
      - laravel

  together_nginx:
    image: nginx:alpine
    container_name: together_nginx
    depends_on:
      - together_api
    ports:
      - "2724:80"   # Host port â†’ Nginx
      - "443:443"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel

  together_db:
    image: bitnami/mariadb:latest
    container_name: together_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: together
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - './docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - db_data:/bitnami/mariadb
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:

