version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        HOST_UID: 1000
        HOST_GID: 1000
        COMPOSER_DEV: false
    container_name: together-php
    expose:
      - 9000

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: together-nginx
    ports:
      - "2724:80" # Host port â†’ Nginx
    depends_on:
      - php
    volumes:
      - ./storage:/var/www/html/storage:rw
      - ./bootstrap/cache:/var/www/html/bootstrap/cache:rw

  db:
    image: bitnami/mariadb:latest
    container_name: together-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: together
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/bitnami/mariadb

volumes:
  db_data:
